<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <table>
        <!-- Table headers -->
        <tr>
            <th>STT</th>
            <th>Mã điểm du lịch</th>
            <th>Tên điểm du lịch</th>
            <th>Tên thành phố</th>
            <th>Đặc trưng</th>
            <th>Actions</th>
        </tr>
        <!-- Table rows generated by PHP -->
        <?php
        $servername = "localhost";
        $username = "root";
        $password = "";
        $dbname = "tourismdb";
        
        $conn = new mysqli($servername, $username, $password, $dbname);
        if ($conn->connect_error) {
            die("Connection Failed! " . $conn->connect_error);
        }
        $stt = 1;
        $sql = "SELECT MaDDL, TenDDL, ttp.TenTTP, DacTrung FROM diemdl ddl JOIN tinhtp ttp ON ddl.MaTTP = ttp.MaTTP";
        $result = $conn->query($sql);
        while($rows = $result->fetch_assoc()){
            echo "<tr id='row_{$rows['MaDDL']}'><td>" . $stt++ . "</td>
                  <td>{$rows['MaDDL']}</td>
                  <td>{$rows['TenDDL']}</td>
                  <td>{$rows['TenTTP']}</td>
                  <td>{$rows['DacTrung']}</td>
                  <td><button onclick=\"viewDDL('{$rows['MaDDL']}', '{$rows['TenDDL']}', '{$rows['TenTTP']}', '{$rows['DacTrung']}')\">View</button> <button onclick=\"deleteDDL('{$rows['MaDDL']}')\">Delete</button></td></tr>";
        }
        ?>
    </table>
    
    <div id="hopdong">
        <form id="updateForm">
            <label for="maddl">Mã điểm du lịch</label>
            <input type="text" id="maddl" name="maddl" readonly>
            <br>
            <label for="tenddl">Tên điểm du lịch</label>
            <input type="text" id="tenddl" name="tenddl">
            <br>
            <select name="mattp" id="mattp">
                <option value="">Chọn thành phố</option>
                <?php
                $sql = "SELECT MaTTP, TenTTP FROM tinhtp";
                $result = $conn->query($sql);
                while($rows = $result->fetch_assoc()){
                    echo "<option value='" . $rows['MaTTP'] . "'>" . $rows['TenTTP'] . "</option>";
                }
                ?>
            </select>
            <br>
            <label for="dactrung">Đặc trưng</label>
            <input type="text" id="dactrung" name="dactrung">
            <button type="button" onclick="updateDiemDL()">Update</button>
        </form>
    </div>
    
    <script>
        function deleteDDL(MaDDL){
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function (){
                if(xhr.readyState == 4 && xhr.status == 200){
                    document.getElementById("row_" + MaDDL).remove();
                }
            };
            xhr.open("GET", "deleteDDL.php?maddl=" + MaDDL, true);
            xhr.send();
        }

        function viewDDL(MaDDL, TenDDL, TenTTP, DacTrung) {
            document.getElementById("maddl").value = MaDDL;
            document.getElementById("tenddl").value = TenDDL;
            var mattpSelect = document.getElementById("mattp");
        for (var i = 0; i < mattpSelect.options.length; i++) {
            if (mattpSelect.options[i].text === TenTTP) {
                mattpSelect.selectedIndex = i;
                break;
            }
        }
            document.getElementById("dactrung").value = DacTrung;
        }

        function updateDiemDL() {
            var formData = new FormData(document.getElementById("updateForm"));
            var xhr = new XMLHttpRequest();
            xhr.onreadystatechange = function () {
                if (xhr.readyState == 4 && xhr.status == 200) {
                    location.reload();
                }
            };
            xhr.open("POST", "updateDiemDL.php", true);
            xhr.send(formData);
        }
    </script>
</body>
</html>